// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zxeowhgddyvhrujqfqgx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp4ZW93aGdkZHl2aHJ1anFmcWd4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE2NDc0NzEsImV4cCI6MjA2NzIyMzQ3MX0.wmNfNtekElJ7smYoB_86AqE03jHezKyCEl0fxYmtPxo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});